name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/sdks/cs/FoldingAtHome.Sdk.sln
    - name: Build
      run: dotnet build src/sdks/cs/FoldingAtHome.Sdk.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/sdks/cs/FoldingAtHome.Test/FoldingAtHome.Test.csproj  --no-restore --verbosity normal
