name: .net core sample app

on:
  push:
    paths:
    - 'src/samples/cs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/samples/cs/FoldingAtHome.Sample/FoldingAtHome.Sample.sln
    - name: Build
      run: dotnet build src/samples/cs/FoldingAtHome.Sample/FoldingAtHome.Sample.sln --configuration Release --no-restore
