name: .net core sdk

on:
  push:
    paths:
    - 'src/sdks/cs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/sdks/cs/FoldingAtHome.Sdk.sln
    - name: Build
      run: dotnet build src/sdks/cs/FoldingAtHome.Sdk.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/sdks/cs/FoldingAtHome.Test/FoldingAtHome.Test.csproj  --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack src/sdks/cs/FoldingAtHome/FoldingAtHome.csproj -p:PackageVersion=0.2.$GITHUB_RUN_NUMBER  --no-restore --no-build --verbosity normal --output src/sdks/cs/FoldingAtHome/nupkgs
    - uses: actions/upload-artifact@v2
      with:
        name: nupkgs
        path: src/sdks/cs/FoldingAtHome/nupkgs
    - name: Publish
      run: dotnet nuget push src/sdks/cs/FoldingAtHome/nupkgs/FoldingAtHome.0.2.$GITHUB_RUN_NUMBER.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
